export { default as About } from "./About";
export { default as AddPost } from "./AddPost";
export { default as Contact } from "./Contact";
export { default as Drafts } from "./Drafts";
export { default as EditPost } from "./EditPost";
export { default as Home } from "./Home";
export { default as NotFound } from "./NotFound";
export { default as Posts } from "./Posts";
export { default as SinglePost } from "./SinglePost";
